# PODNAME: mop::manual::intro
# ABSTRACT: A manual for p5-mop

__END__

=pod

=head1 NAME

mop::manual::intro - A manual for p5-mop

=head1 DESCRIPTION

This is the first attempt at a manual for the 
p5-mop, it is very much a work in progress. You 
can expect gaps and inconsistency in these 
early versions. 

Patches are always welcome :)

=head1 SECTIONS

=over 4

=item L<Classes>

=item L<Attributes>

=item L<Methods>

=item L<Roles>

=item L<Traits>

=back

=head1 AUTHOR

Stevan Little <stevan.little@iinteractive.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Infinity Interactive.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut