<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Perl mop</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>source.perl</string>
            </dict>
            <dict>
                <key>applyEndPatternLast</key>
                <integer>1</integer>
                <key>begin</key>
                <string>^\s*(class|role)\s+([^;\s]+)</string>
                <key>end</key>
                <string>^\s*\}$\n?</string>
                <key>name</key>
                <string>meta.class.mop</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.mop</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.class.mop</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>^\s*(method)\s+([-a-zA-Z0-9_]+)\s*(\([\$\@\*;]*\))?</string>
                        <key>name</key>
                        <string>meta.function.mop</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.sub.mop</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.function.mop</string>
                            </dict>
                            <key>3</key>
                            <dict>
                                <key>name</key>
                                <string>variable.parameter.function.mop</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>source.perl</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(extends|with|is|does)\s+([^;\s]+)</string>
                        <key>name</key>
                        <string>keyword.control.mop</string>
                        <key>captures</key>
                        <dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>entity.name.type.class.mop</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\$!)[A-Za-z_][A-Za-z0-9_]*\b</string>
                        <key>name</key>
                        <string>punctuation.definition.variable.perl</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.variable.perl</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(has)\b</string>
                        <key>name</key>
                        <string>storage.modifier.mop</string>
                    </dict>
                </array>
            </dict>
        </array>
        <key>scopeName</key>
        <string>source.mop</string>
        <key>uuid</key>
        <string>EDBFE125-6B1C-11D9-9189-000D93589AF7</string>
    </dict>
</plist>
